apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wbfly7noj-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wbfly7noj-python 
  name: wbfly7noj-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wbfly7noj-python 
